#!/usr/bin/env python

Import("env")

# Clone build environment for my module
env_module = env.Clone(
  SCONS_CXX_STANDARD='c++20',
  CCFLAGS=['--std=c++20']
)

# External library paths
env_module.Append(CPPPATH=["../../../../3rdparty/gmlib/libs/gmconcepts/include"])
env_module.Append(CPPPATH=["../../../../3rdparty/gmlib/include"])
env_module.Append(CPPPATH=["../../../../physengine/include"])


# Add source-files for my module
env_module.add_source_files(env_module.modules_sources, "*.cpp")

SConscript("joints/SCsub")
